site_name: Khalti Services Documentation
nav:
  - Introduction: index.md
  - Service Status Check : 
      - State List: Servicescodes/statecode.md
      - DLR: Servicescodes/dlr.md
      - Service Balance Check: Servicescodes/balance_check.md
      - Service LookUp API: Servicescodes/lookup.md
      - Bulk Service Lookup: Servicescodes/bulkservice.md
  - Mobile TopUp:
        - Khalti Topup: Khaltitopup/khaltitopup.md
        - NTC: MobileTopup/nepal_telecom.md
        - Ncell: MobileTopup/ncell.md
  - Data Packs:
      - Ncell DataPacks: datapacks/NcellProduct.md
      - NTC DataPacks: datapacks/ntcProduct.md

      
  - Electricity: Electricity/nea.md
  - Khanepani: 
      - Community Khanepani: Khanepani/khanepani.md
      - Kukl:
          - Counter : Khanepani/Kukl/counter.md 
          - Kukl Details: Khanepani/Kukl/Kukl-Details.md
          - Kukl Service Charge: servicecharge/service-charge.md
          - KUKL Payment: Khanepani/Kukl/Kukl-payment.md

  - TV :
    - Nettv:  TV/nettv.md
    - SimTV: TV/simtv.md
    - Max Tv: TV/maxtv.md
    - Dishhome: Internet/dishhome.md
    - Prabhu Tv: TV/Prabhutv.md
    - P & G Network: TV/p&g.md
    - Jagriti Cable: TV/jagrititv.md
    - Times: TV/times.md

  - Internet:
    - Worldlink: Internet/worldlink.md
    - Vianet: Internet/vianet-new.md
    - Adsl: Internet/adsl.md
    - NTFTTH : Internet/ntftth.md
    - Dishhome: Internet/dishhome.md
    - Subisu: Internet/subisu.md
    - Classic Tech: Internet/classictech.md
    - Wifi Nepal: Internet/wifi-nepal.md
    - Broadlink: Internet/broadlink.md
    - Times Internet: Internet/timesinternet.md
    - Arrownet: Internet/arrownet.md
    - Virtual Network: Internet/Virtual-network.md
    - Web Network: Internet/web-network.md
    - Royal Network: Internet/royal-network.md
    - Techminds: Internet/techminds.md
    - East Link : Internet/eastlink.md
    - Metrolink: Internet/metrolink.md
    - Infonet Communication: Internet/infonet.md
    - Pokhara Internet: Internet/pokhara-internet.md
    - Nijgad Cable: Internet/nijgad_cable.md
    - Net Max: Internet/netmax.md
    - Dolfin Internet: Internet/dolfin-internet.md
    - HashCNet V1: Internet/hashcnet/v1.md
    - HashCNet V2: Internet/hashcnet/v2.md
    - Fibertel Fibernet: Internet/Fibertel.md
    - Rapid Unique Net: Internet/rapidapi.md
    - GRS Internet: Internet/grs-internet.md
    - Infonet Technology: Internet/infonet.md
    - Merosoft: Internet/merosoft.md
    - Konnect: Internet/konnect.md
    - Kriti Darshan: Internet/kriti-darshan.md
    - Chitrawan Unique Net: Internet/chitrawan.md
    - Airlink Communication: Internet/airlink.md
    - 3G Vision: Internet/3g-vision.md
    - First Link: Internet/first-link.md
    - Sky Broadband: Internet/sky-broadband.md
    

  - Insurance: 
      - Non life Insurances:
          - Arhant Non-Life Insurances: Insurance/Arhant Insurance/non_life.md 
          - Prudential Insurance: Insurance/prudential/prudential.md
          - Neco Insurance:  Insurance/neco_insurance.md
          - Sagarmatha Lumbini Insurance: Insurance/sagarmatha_insurance.md
          - Nepal Non Life Insurance: Insurance/nepal_non_life.md

  
      - Life Insurances:
        - Arhant Life Insurance : Insurance/Arhant Insurance/life.md 
        - Surya Life Insurance: Insurance/surya/Suryalife.md
        - Sanima Insurance: Insurance/Reliance Insurance/reliance_insurance.md    
        - Sun Life Insurance: Insurance/Sunlife/sunlife.md
        - Rastriya Beema Sansthan: Insurance/rastriyabeema.md
        - Surya Jyoti Loan Repayment: Insurance/suryajoytiloan.md
        - Reliable Insurance: Insurance/Reliable_life.md
        - Citizen Life Insurance: Insurance/Citizen/citizen.md
        - Surya Life Insurance First Payment:  Insurance/surya/surya_life_insurance.md
        - IME General Insurance: Insurance/ime/ime_general.md
        # - Prabhu Life: Insurance/prabhu_life.md (Updated to Arahnt Life Insurance)
        - Nepal Life Insurance: Insurance/Nepal/nepal_Life_Insurace.md
        
  

  - EMI:
    - Maw EMI: maw/maw.md

  - Community Electricity:
    - Himchuli Electricity: Electricity/Himchuli.md
    - Watermark Electricity: Electricity/watermark.md
    - Dreamer Electricity: Electricity/dreamer.md
    - Softlab Electricity: Electricity/softlab.md

  - Cable Car: Cable Car/cablecar.md

  - Antivirus:
      - Kaspersky Antivirus: antivirus/kaspersky.md
      - Eset Antivirus: antivirus/eset.md
      - K7 Antivirus: antivirus/k7.md
      - Wardwiz Antivirus: antivirus/wardwiz.md
      - Mcafee Antivirus: antivirus/mcafee.md


  - Ride:
      - CABTM: Ride/cabtm.md
      - Tottle: Ride/tootle.md

  - Bluebook: bluebook/bluebook.md
  - PSTN (Landline): PSTN/landline.md
  - Bus: 
    - Routes: Bus/route.md
    - Search: Bus/search.md
    - Seat: Bus/seat.md
    - Book Bus: Bus/bus-booking.md
    - Add info: Bus/add-info.md
    - Payment: Bus/payment.md
    - Download Ticket: Bus/ticket-download.md
  - Social Security Fund: ssf/ssf.md



  - Flight:
    - Sector : flight/sector.md 
    - Search Flight: flight/search.md
    - Book Flight: flight/book.md
    - Add info: flight/addinfo.md
    - Issue Ticket: flight/issue.md
    - Cancel Flight: flight/cancel.md
    - Ticket Download: flight/ticketdownload.md
    - Flight LookUp: flight/flight-lookup.md
    - Flight Status: flight/flightstatus.md
    - Flight Info: flight/info.md  
    - Flight FAQ: flight/faq.md

  - Rc Card: Rc card/rccard.md

  - Changelog: Servicescodes/changelog.md
  - FAQ's: Servicescodes/faq.md


theme:
  name: material
  custom_dir: overrides
  favicon: "https://d7vw40z4bofef.cloudfront.net/static/2.59.12-web19/images/favicon.png"
  icon:
    logo: "img/khalti_logo"
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - style/custom.css
  - style/extra.css
docs_dir: content 
site_dir: docs

copyright: "Copyright &copy; 2025 Khalti Private Limited"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/khalti"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/KhaltiOfficial"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/company/khalti-digital-wallet"
    - icon: "fontawesome/brands/facebook"
      link: "https://facebook.com/khaltiofficial"
    - icon: "fontawesome/brands/instagram"
      link: "https://www.instagram.com/khaltiofficial/"

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences

# Uncomment and install any necessary plugins if needed
# plugins:
#   - search
#   - social
